Action2 remove button
spacelabdev/spacelab-react pull request #220
Opened 2022-11-08 04:27 UTC by DrDrewCain

2022-11-08 04:34 UTC, DrDrewCain reviewed
Should be set for merging, if there is any issue let me know.

2022-11-10 16:29 UTC, bcantello requested changes
This information will used exactly as is soon. It should not be deleted. It should be commented out for the time being and as TODO statement should be added with details about when the code can be uncommented.

2022-11-10 16:31 UTC, DrDrewCain commented
> This information will used exactly as is soon. It should not be deleted. It should be commented out for the time being and a TODO statement should be added with details about when the code can be uncommented.

Alright got it. I'll fix that, thanks for letting me know.

2022-11-10 17:21 UTC, bcantello commented
> > This information will used exactly as is soon. It should not be deleted. It should be commented out for the time being and a TODO statement should be added with details about when the code can be uncommented.
> 
> Only thing is as far as I can tell, it's to be disabled until future release but what that "future" release entails I am not certain, I would need to reach out to Alex maybe he has some ideas @aanand93

Basically the TODO should state that the code should be uncommented once we are ready to implement the cohorts tab and move team members from the active team to their respective cohorts.

2022-11-10 17:29 UTC, DrDrewCain commented
> > > This information will used exactly as is soon. It should not be deleted. It should be commented out for the time being and a TODO statement should be added with details about when the code can be uncommented.
> > 
> > 
> > Only thing is as far as I can tell, it's to be disabled until future release but what that "future" release entails I am not certain, I would need to reach out to Alex maybe he has some ideas @aanand93
> 
> Basically the TODO should state that the code should be uncommented once we are ready to implement the cohorts tab and move team members from the active team to their respective cohorts.

Ah okay, got it. Thanks for the clarification Brandon, I'll add that change.

2022-11-10 17:37 UTC, bcantello requested changes

2022-11-10 17:37 UTC, bcantello commented on src/pages/about/aboutHelper.js
> -		{
This will all be used. No need to delete or comment. Just leave as is.

2022-11-10 17:37 UTC, bcantello commented on src/pages/about/aboutHelper.js
> -		{
This will all be use. Do not delete or comment. Just leave as is

2022-11-10 17:37 UTC, bcantello commented on src/pages/about/aboutTeamSliderSection.js
>  			<div className="about-team-toggle">
This container div should be commented as well

2022-11-10 17:37 UTC, bcantello commented on src/pages/about/aboutHelper.js
> +		},
Add extra white space at top and bottom of this group that has been added. Add a TODO comment that lets us know that this group can be deleted when cohorts are implemented.

2022-11-15 03:48 UTC, bcantello approved these changes

2022-11-15 03:48 UTC, merged